/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_win_main (void);
GtkWidget* create_win_payout (void);
GtkWidget* create_win_acceptors (void);
GtkWidget* create_win_leds (void);
GtkWidget* create_win_dispensers (void);
