/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aes_imhei_AESImhei_EventDetailBlock */

#ifndef _Included_aes_imhei_AESImhei_EventDetailBlock
#define _Included_aes_imhei_AESImhei_EventDetailBlock
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
