/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aes_imhei_AESImhei_AcceptorBlock */

#ifndef _Included_aes_imhei_AESImhei_AcceptorBlock
#define _Included_aes_imhei_AESImhei_AcceptorBlock
#ifdef __cplusplus
extern "C" {
#endif
#undef aes_imhei_AESImhei_AcceptorBlock_MAX_ACCEPTOR_COINS
#define aes_imhei_AESImhei_AcceptorBlock_MAX_ACCEPTOR_COINS 256L
#ifdef __cplusplus
}
#endif
#endif
